apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090

  - name: Tempo
    type: tempo
    uid: P214B5B846CF3925F
    access: proxy
    url: http://tempo:3200
    jsonData:
      serviceMap:
        datasourceUid: 'PBFA97CFB590B2093'
      nodeGraph:
        enabled: true
