#!/usr/bin/env bash
//MISE description="Start a dev server with air."

source "${BASH_SOURCE[0]%/*}/lib/modules.sh"

ALIAS=$1

if [[ -z "$ALIAS" ]]; then
    echo "Error: Alias is required for run."
    echo "Available: ${MODULES_ALIASES[*]}"
    exit 1
fi

TARGET_PATH="${MODULES_PATH[$ALIAS]}"
TARGET_CMD="${MODULES_CMD[$ALIAS]}"

if [[ -z "$TARGET_CMD" ]]; then
    echo "Error: Alias '$ALIAS' does not have a cmd path (maybe it's a pkg?)."
    exit 1
fi

echo "Running service '$ALIAS'..."
mise exec -C "$TARGET_PATH" -- air
