version: "2"

run:
  timeout: 5m
  tests: true
  relative-path-mode: gomod
  modules-download-mode: readonly
  issues-exit-code: 1
  allow-parallel-runners: false

linters:
  default: all
  
  disable:
    # Deprecated: use gomodguard_v2 instead.
    - gomodguard

    # Deprecated: use wsl_v5 instead.
    - wsl

    # use inline error
    - noinlineerr

  exclusions:
    generated: strict
    warn-unused: true

  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - "$all"
          allow:
            - "$gostd"
            - "github.com/CubeLitBlade/community-v2/backend"
            - "github.com/gin-gonic/gin"
            - "github.com/gorilla/csrf"
            - "golang.org/x/crypto/bcrypt"
            - "gorm.io/gorm"
            - "gorm.io/driver/postgres"

    errcheck:
      check-type-assertions: true
      check-blank: true
      disable-default-exclusions: true
      verbose: true

    errchkjson:
      check-error-free-encoding: true
      report-no-exported: true

    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true

    govet:
      enable-all: true

    gocritic:
      enable-all: true

    revive:
      severity: error
      enable-all-rules: true
      confidence: 0.1
      directives:
        - name: specify-disable-reason
          severity: error
      rules:
        - name: add-constant
          arguments:
            - allow-strs: '""'
              allow-ints: "0,1,2"
              allow-floats: "0.0,0.,1.0,1.,2.0,2."

    nolintlint:
      allow-unused: false
      allow-no-explanation: []
      require-explanation: true
      require-specific: true

    nilnil:
      only-two: false
      detect-opposite: true

    nonamedreturns:
      report-error-in-defer: true

    paralleltest:
      ignore-missing: false
      ignore-missing-subtests: false
      check-cleanup: true

    reassign:
      patterns:
        - ".*"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
    - gci

  exclusions:
    generated: strict
    warn-unused: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false

severity:
  default: error