services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  otel-collector:
    ports:
      - "4317:4317"
  jaeger:
    ports:
      - "16686:16686"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  openfga:
    ports:
      - "9090:8080"
      - "9091:8081"
      - "2112:2112"
