package events

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"sync"
	"time"

	"github.com/Azure/go-amqp"
	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

const defaultConsumerCloseTimeout = 30 * time.Second

// ExchangeConsumerConfig holds the configuration options for initializing an ExchangeConsumer.
type ExchangeConsumerConfig struct {
	BrokerURL      string
	Logger         *slog.Logger
	ExchangeName   string
	Keys           []string
	InitialCredits int32
	CloseTimeout   time.Duration
}

// ExchangeConsumer consumes messages from a RabbitMQ exchange and delivers them via the Deliveries channel.
type ExchangeConsumer struct {
	cfg    *ExchangeConsumerConfig
	logger *slog.Logger

	conn     *rmq.AmqpConnection
	env      *rmq.Environment
	consumer *rmq.Consumer

	mu        sync.RWMutex
	available bool
	wg        sync.WaitGroup

	consumeCancel context.CancelFunc

	Deliveries chan *ReceivedMessage
}

// NewExchangeConsumer creates and returns a new instance of ExchangeConsumer.
func NewExchangeConsumer(cfg *ExchangeConsumerConfig) *ExchangeConsumer {
	if cfg.Logger == nil {
		cfg.Logger = slog.Default()
	}
	if cfg.CloseTimeout == 0 {
		cfg.CloseTimeout = defaultConsumerCloseTimeout
	}
	if cfg.InitialCredits == 0 {
		cfg.InitialCredits = 10
	}

	return &ExchangeConsumer{
		cfg:           cfg,
		logger:        cfg.Logger,
		conn:          nil,
		env:           rmq.NewEnvironment(cfg.BrokerURL, nil),
		consumer:      nil,
		mu:            sync.RWMutex{},
		available:     false,
		wg:            sync.WaitGroup{},
		consumeCancel: nil,
		Deliveries:    nil,
	}
}

// Init establishes the connection to the broker, declares the exchange and an exclusive queue,
// binds the specified routing keys, and starts the consume loop.
func (c *ExchangeConsumer) Init(ctx context.Context) error {
	conn, err := c.env.NewConnection(ctx)
	if err != nil {
		c.closeConn(ctx)
		c.cfg.Logger.Error("Failed to connect to RabbitMQ", "error", err)
		return fmt.Errorf("unable to connect to broker: %w", err)
	}
	c.conn = conn

	_, err = conn.Management().DeclareExchange(ctx, &rmq.DirectExchangeSpecification{
		Name: c.cfg.ExchangeName,
	})
	if err != nil {
		c.closeConn(ctx)
		c.cfg.Logger.Error("Failed to declare exchange", "error", err)
		return fmt.Errorf("unable to declare exchange: %w", err)
	}

	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  true,
		IsAutoDelete: true,
	})
	if err != nil {
		c.closeConn(ctx)
		c.cfg.Logger.Error("Failed to declare queue", "error", err)
		return fmt.Errorf("unable to declare queue: %w", err)
	}

	for _, key := range c.cfg.Keys {
		_, err = conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
			SourceExchange:   c.cfg.ExchangeName,
			DestinationQueue: qInfo.Name(),
			BindingKey:       key,
		})
		if err != nil {
			c.closeConn(ctx)
			c.cfg.Logger.Error("Failed to bind to queue", "error", err, "key", key)
			return fmt.Errorf("unable to bind to queue: %w", err)
		}
	}

	consumer, err := conn.NewConsumer(ctx, qInfo.Name(), &rmq.ConsumerOptions{
		InitialCredits: c.cfg.InitialCredits,
	})
	if err != nil {
		c.closeConn(ctx)
		c.cfg.Logger.Error("Failed to create consumer", "error", err)
		return fmt.Errorf("unable to create consumer: %w", err)
	}
	c.consumer = consumer

	consumeCtx, consumeCancel := context.WithCancel(ctx)
	c.consumeCancel = consumeCancel

	c.Deliveries = make(chan *ReceivedMessage, c.cfg.InitialCredits)
	c.wg.Add(1)
	go c.consumeLoop(consumeCtx)

	c.mu.Lock()
	c.available = true
	c.mu.Unlock()

	return nil
}

// Close gracefully shuts down the consumer, cancels the consume loop, waits for in-flight
// messages, and closes the AMQP connections.
func (c *ExchangeConsumer) Close() error {
	c.mu.Lock()
	c.available = false
	c.mu.Unlock()

	if c.consumeCancel != nil {
		c.consumeCancel()
	}

	c.wg.Wait()
	c.logger.Debug("Consumer loop stopped gracefully.")

	ctx, cancel := context.WithTimeout(context.Background(), c.cfg.CloseTimeout)
	defer cancel()

	var errs []error

	if c.consumer != nil {
		if err := c.consumer.Close(ctx); err != nil {
			c.logger.Error("Failed to close consumer", "error", err)
			errs = append(errs, err)
		}
	}

	if err := c.env.CloseConnections(ctx); err != nil {
		c.logger.Error("Failed to close connections", "error", err)
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errors.Join(errs...)
	}
	return nil
}

func (c *ExchangeConsumer) consumeLoop(ctx context.Context) {
	defer c.wg.Done()
	defer close(c.Deliveries)

	for {
		delivery, err := c.consumer.Receive(ctx)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				c.logger.Debug("Consumer loop exiting due to shutdown signal.")
				return
			}

			c.logger.Error("Failed to receive message, consumer exiting.", "error", err)
			return
		}

		msg := delivery.Message()
		var content string
		if len(msg.Data) > 0 {
			content = string(msg.Data[0])
		}

		received := &ReceivedMessage{
			Content:     content,
			acceptFunc:  func() error { return delivery.Accept(ctx) },
			requeueFunc: func() error { return delivery.Requeue(ctx) },
			discardFunc: func(e *amqp.Error) error { return delivery.Discard(ctx, e) },
		}

		select {
		case c.Deliveries <- received:
		case <-ctx.Done():
			if err := received.Requeue(); err != nil {
				c.logger.Error("Failed to nack message", "error", err)
			}
			return
		}
	}
}

func (c *ExchangeConsumer) closeConn(ctx context.Context) {
	if err := c.env.CloseConnections(ctx); err != nil {
		c.logger.Error("Failed to close connections", "error", err)
	}
}
