package amqp

import (
	"context"
	"fmt"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

func Connect(ctx context.Context, env *rmq.Environment) (*rmq.AmqpConnection, error) {
	conn, err := env.NewConnection(ctx)
	if err != nil {
		return nil, fmt.Errorf("unable to connect to broker: %w", err)
	}

	return conn, nil
}

func DeclareTopicExchange(ctx context.Context, conn *rmq.AmqpConnection, name string) error {
	_, err := conn.Management().DeclareExchange(ctx, &rmq.TopicExchangeSpecification{
		Name: name,
	})
	if err != nil {
		return fmt.Errorf("unable to declare exchange: %w", err)
	}

	return nil
}

func DeclareExclusiveQueue(ctx context.Context, conn *rmq.AmqpConnection) (*rmq.AmqpQueueInfo, error) {
	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  true,
		IsAutoDelete: true,
	})
	if err != nil {
		return nil, fmt.Errorf("unable to declare queue: %w", err)
	}

	return qInfo, nil
}

func BindExchangeToQueue(
	ctx context.Context, conn *rmq.AmqpConnection, sourceExchange string, destinationQueue string, keys []string,
) error {
	for _, key := range keys {
		_, err := conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
			SourceExchange:   sourceExchange,
			DestinationQueue: destinationQueue,
			BindingKey:       key,
		})
		if err != nil {
			return fmt.Errorf("unable to bind exchange to queue: %w", err)
		}
	}

	return nil
}
