// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cubelitblade/community-v2/backend/services/post/internal/adapter/driven/persistence/ent/outbox"
)

// OutboxCreate is the builder for creating a Outbox entity.
type OutboxCreate struct {
	config
	mutation *OutboxMutation
	hooks    []Hook
}

// SetAggregateID sets the "aggregate_id" field.
func (_c *OutboxCreate) SetAggregateID(v int64) *OutboxCreate {
	_c.mutation.SetAggregateID(v)
	return _c
}

// SetAggregateType sets the "aggregate_type" field.
func (_c *OutboxCreate) SetAggregateType(v string) *OutboxCreate {
	_c.mutation.SetAggregateType(v)
	return _c
}

// SetTopic sets the "topic" field.
func (_c *OutboxCreate) SetTopic(v string) *OutboxCreate {
	_c.mutation.SetTopic(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *OutboxCreate) SetEventType(v string) *OutboxCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *OutboxCreate) SetPayload(v map[string]interface{}) *OutboxCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OutboxCreate) SetCreatedAt(v time.Time) *OutboxCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OutboxCreate) SetNillableCreatedAt(v *time.Time) *OutboxCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *OutboxCreate) SetPublishedAt(v time.Time) *OutboxCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *OutboxCreate) SetNillablePublishedAt(v *time.Time) *OutboxCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetTraceID sets the "trace_id" field.
func (_c *OutboxCreate) SetTraceID(v string) *OutboxCreate {
	_c.mutation.SetTraceID(v)
	return _c
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_c *OutboxCreate) SetNillableTraceID(v *string) *OutboxCreate {
	if v != nil {
		_c.SetTraceID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OutboxCreate) SetID(v int64) *OutboxCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OutboxMutation object of the builder.
func (_c *OutboxCreate) Mutation() *OutboxMutation {
	return _c.mutation
}

// Save creates the Outbox in the database.
func (_c *OutboxCreate) Save(ctx context.Context) (*Outbox, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OutboxCreate) SaveX(ctx context.Context) *Outbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboxCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboxCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OutboxCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := outbox.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OutboxCreate) check() error {
	if _, ok := _c.mutation.AggregateID(); !ok {
		return &ValidationError{Name: "aggregate_id", err: errors.New(`ent: missing required field "Outbox.aggregate_id"`)}
	}
	if _, ok := _c.mutation.AggregateType(); !ok {
		return &ValidationError{Name: "aggregate_type", err: errors.New(`ent: missing required field "Outbox.aggregate_type"`)}
	}
	if _, ok := _c.mutation.Topic(); !ok {
		return &ValidationError{Name: "topic", err: errors.New(`ent: missing required field "Outbox.topic"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "Outbox.event_type"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "Outbox.payload"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Outbox.created_at"`)}
	}
	return nil
}

func (_c *OutboxCreate) sqlSave(ctx context.Context) (*Outbox, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OutboxCreate) createSpec() (*Outbox, *sqlgraph.CreateSpec) {
	var (
		_node = &Outbox{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(outbox.Table, sqlgraph.NewFieldSpec(outbox.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AggregateID(); ok {
		_spec.SetField(outbox.FieldAggregateID, field.TypeInt64, value)
		_node.AggregateID = value
	}
	if value, ok := _c.mutation.AggregateType(); ok {
		_spec.SetField(outbox.FieldAggregateType, field.TypeString, value)
		_node.AggregateType = value
	}
	if value, ok := _c.mutation.Topic(); ok {
		_spec.SetField(outbox.FieldTopic, field.TypeString, value)
		_node.Topic = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(outbox.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(outbox.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(outbox.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(outbox.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.TraceID(); ok {
		_spec.SetField(outbox.FieldTraceID, field.TypeString, value)
		_node.TraceID = &value
	}
	return _node, _spec
}

// OutboxCreateBulk is the builder for creating many Outbox entities in bulk.
type OutboxCreateBulk struct {
	config
	err      error
	builders []*OutboxCreate
}

// Save creates the Outbox entities in the database.
func (_c *OutboxCreateBulk) Save(ctx context.Context) ([]*Outbox, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Outbox, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OutboxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OutboxCreateBulk) SaveX(ctx context.Context) []*Outbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboxCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboxCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
