// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cubelitblade/community-v2/backend/services/post/internal/adapter/driven/persistence/ent/outbox"
	"github.com/cubelitblade/community-v2/backend/services/post/internal/adapter/driven/persistence/ent/predicate"
)

// OutboxUpdate is the builder for updating Outbox entities.
type OutboxUpdate struct {
	config
	hooks    []Hook
	mutation *OutboxMutation
}

// Where appends a list predicates to the OutboxUpdate builder.
func (_u *OutboxUpdate) Where(ps ...predicate.Outbox) *OutboxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *OutboxUpdate) SetAggregateID(v int64) *OutboxUpdate {
	_u.mutation.ResetAggregateID()
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableAggregateID(v *int64) *OutboxUpdate {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// AddAggregateID adds value to the "aggregate_id" field.
func (_u *OutboxUpdate) AddAggregateID(v int64) *OutboxUpdate {
	_u.mutation.AddAggregateID(v)
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *OutboxUpdate) SetAggregateType(v string) *OutboxUpdate {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableAggregateType(v *string) *OutboxUpdate {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// SetTopic sets the "topic" field.
func (_u *OutboxUpdate) SetTopic(v string) *OutboxUpdate {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableTopic(v *string) *OutboxUpdate {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OutboxUpdate) SetEventType(v string) *OutboxUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableEventType(v *string) *OutboxUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OutboxUpdate) SetPayload(v map[string]interface{}) *OutboxUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OutboxUpdate) SetCreatedAt(v time.Time) *OutboxUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableCreatedAt(v *time.Time) *OutboxUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *OutboxUpdate) SetPublishedAt(v time.Time) *OutboxUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillablePublishedAt(v *time.Time) *OutboxUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *OutboxUpdate) ClearPublishedAt() *OutboxUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetTraceID sets the "trace_id" field.
func (_u *OutboxUpdate) SetTraceID(v string) *OutboxUpdate {
	_u.mutation.SetTraceID(v)
	return _u
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_u *OutboxUpdate) SetNillableTraceID(v *string) *OutboxUpdate {
	if v != nil {
		_u.SetTraceID(*v)
	}
	return _u
}

// ClearTraceID clears the value of the "trace_id" field.
func (_u *OutboxUpdate) ClearTraceID() *OutboxUpdate {
	_u.mutation.ClearTraceID()
	return _u
}

// Mutation returns the OutboxMutation object of the builder.
func (_u *OutboxUpdate) Mutation() *OutboxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OutboxUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OutboxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OutboxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(outbox.Table, outbox.Columns, sqlgraph.NewFieldSpec(outbox.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(outbox.FieldAggregateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAggregateID(); ok {
		_spec.AddField(outbox.FieldAggregateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(outbox.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(outbox.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(outbox.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(outbox.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(outbox.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(outbox.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(outbox.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TraceID(); ok {
		_spec.SetField(outbox.FieldTraceID, field.TypeString, value)
	}
	if _u.mutation.TraceIDCleared() {
		_spec.ClearField(outbox.FieldTraceID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OutboxUpdateOne is the builder for updating a single Outbox entity.
type OutboxUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OutboxMutation
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *OutboxUpdateOne) SetAggregateID(v int64) *OutboxUpdateOne {
	_u.mutation.ResetAggregateID()
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableAggregateID(v *int64) *OutboxUpdateOne {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// AddAggregateID adds value to the "aggregate_id" field.
func (_u *OutboxUpdateOne) AddAggregateID(v int64) *OutboxUpdateOne {
	_u.mutation.AddAggregateID(v)
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *OutboxUpdateOne) SetAggregateType(v string) *OutboxUpdateOne {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableAggregateType(v *string) *OutboxUpdateOne {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// SetTopic sets the "topic" field.
func (_u *OutboxUpdateOne) SetTopic(v string) *OutboxUpdateOne {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableTopic(v *string) *OutboxUpdateOne {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *OutboxUpdateOne) SetEventType(v string) *OutboxUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableEventType(v *string) *OutboxUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *OutboxUpdateOne) SetPayload(v map[string]interface{}) *OutboxUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OutboxUpdateOne) SetCreatedAt(v time.Time) *OutboxUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableCreatedAt(v *time.Time) *OutboxUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *OutboxUpdateOne) SetPublishedAt(v time.Time) *OutboxUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillablePublishedAt(v *time.Time) *OutboxUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *OutboxUpdateOne) ClearPublishedAt() *OutboxUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetTraceID sets the "trace_id" field.
func (_u *OutboxUpdateOne) SetTraceID(v string) *OutboxUpdateOne {
	_u.mutation.SetTraceID(v)
	return _u
}

// SetNillableTraceID sets the "trace_id" field if the given value is not nil.
func (_u *OutboxUpdateOne) SetNillableTraceID(v *string) *OutboxUpdateOne {
	if v != nil {
		_u.SetTraceID(*v)
	}
	return _u
}

// ClearTraceID clears the value of the "trace_id" field.
func (_u *OutboxUpdateOne) ClearTraceID() *OutboxUpdateOne {
	_u.mutation.ClearTraceID()
	return _u
}

// Mutation returns the OutboxMutation object of the builder.
func (_u *OutboxUpdateOne) Mutation() *OutboxMutation {
	return _u.mutation
}

// Where appends a list predicates to the OutboxUpdate builder.
func (_u *OutboxUpdateOne) Where(ps ...predicate.Outbox) *OutboxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OutboxUpdateOne) Select(field string, fields ...string) *OutboxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Outbox entity.
func (_u *OutboxUpdateOne) Save(ctx context.Context) (*Outbox, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OutboxUpdateOne) SaveX(ctx context.Context) *Outbox {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OutboxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OutboxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OutboxUpdateOne) sqlSave(ctx context.Context) (_node *Outbox, err error) {
	_spec := sqlgraph.NewUpdateSpec(outbox.Table, outbox.Columns, sqlgraph.NewFieldSpec(outbox.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Outbox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, outbox.FieldID)
		for _, f := range fields {
			if !outbox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != outbox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(outbox.FieldAggregateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAggregateID(); ok {
		_spec.AddField(outbox.FieldAggregateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(outbox.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(outbox.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(outbox.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(outbox.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(outbox.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(outbox.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(outbox.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TraceID(); ok {
		_spec.SetField(outbox.FieldTraceID, field.TypeString, value)
	}
	if _u.mutation.TraceIDCleared() {
		_spec.ClearField(outbox.FieldTraceID, field.TypeString)
	}
	_node = &Outbox{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{outbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
