// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AccountProfile is the predicate function for accountprofile builders.
type AccountProfile func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)
