// Package amqp provides internal helpers for managing AMQP topologies and connections.
package amqp

import (
	"context"
	"fmt"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

// Connect establishes a new AMQP connection using the provided environment.
func Connect(ctx context.Context, env *rmq.Environment) (*rmq.AmqpConnection, error) {
	conn, err := env.NewConnection(ctx)
	if err != nil {
		return nil, fmt.Errorf("unable to connect to broker: %w", err)
	}

	return conn, nil
}

// DeclareTopicExchange declares a topic exchange with the given name on the connection.
func DeclareTopicExchange(ctx context.Context, conn *rmq.AmqpConnection, name string) error {
	_, err := conn.Management().DeclareExchange(ctx, &rmq.TopicExchangeSpecification{
		Name: name,
	})
	if err != nil {
		return fmt.Errorf("unable to declare exchange: %w", err)
	}

	return nil
}

// DeclareExclusiveQueue declares an exclusive, auto-delete queue on the connection.
func DeclareExclusiveQueue(ctx context.Context, conn *rmq.AmqpConnection) (*rmq.AmqpQueueInfo, error) {
	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  true,
		IsAutoDelete: true,
	})
	if err != nil {
		return nil, fmt.Errorf("declare auto generated queue: %w", err)
	}

	return qInfo, nil
}

// DeclareQuorumQueue declares a named quorum queue on the connection.
func DeclareQuorumQueue(ctx context.Context, conn *rmq.AmqpConnection, queueName string) (*rmq.AmqpQueueInfo, error) {
	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.QuorumQueueSpecification{
		Name: queueName,
	})
	if err != nil {
		return nil, fmt.Errorf("declare quorum queue: %w", err)
	}

	return qInfo, nil
}

// BindExchangeToQueue binds a source exchange to a destination queue using the specified routing keys.
func BindExchangeToQueue(
	ctx context.Context, conn *rmq.AmqpConnection, sourceExchange string, destinationQueue string, keys []string,
) error {
	for _, key := range keys {
		_, err := conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
			SourceExchange:   sourceExchange,
			DestinationQueue: destinationQueue,
			BindingKey:       key,
		})
		if err != nil {
			return fmt.Errorf("unable to bind exchange to queue: %w", err)
		}
	}

	return nil
}
