// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountProfilesColumns holds the columns for the "account_profiles" table.
	AccountProfilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "username", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString},
	}
	// AccountProfilesTable holds the schema information for the "account_profiles" table.
	AccountProfilesTable = &schema.Table{
		Name:       "account_profiles",
		Columns:    AccountProfilesColumns,
		PrimaryKey: []*schema.Column{AccountProfilesColumns[0]},
	}
	// OutboxColumns holds the columns for the "outbox" table.
	OutboxColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "aggregate_id", Type: field.TypeInt64},
		{Name: "aggregate_type", Type: field.TypeString},
		{Name: "topic", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeString},
		{Name: "payload", Type: field.TypeJSON},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "trace_id", Type: field.TypeString, Nullable: true},
	}
	// OutboxTable holds the schema information for the "outbox" table.
	OutboxTable = &schema.Table{
		Name:       "outbox",
		Columns:    OutboxColumns,
		PrimaryKey: []*schema.Column{OutboxColumns[0]},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Nullable: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"published", "archived"}, Default: "published"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "author_id", Type: field.TypeInt64, Nullable: true},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "posts_account_profiles_author",
				Columns:    []*schema.Column{PostsColumns[6]},
				RefColumns: []*schema.Column{AccountProfilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountProfilesTable,
		OutboxTable,
		PostsTable,
	}
)

func init() {
	OutboxTable.Annotation = &entsql.Annotation{
		Table: "outbox",
	}
	PostsTable.ForeignKeys[0].RefTable = AccountProfilesTable
}
