[account]
# Name of this service.
service_name = "account"

# Runtime environment.
# Should be one of: 'dev' or 'prod'.
env = "dev"

# Addr for http server.
http_addr = ":8080"

[account.database]
# Connection string of database.
url = "postgres://account_service_svc:account_service_svc_password@localhost:5432/community?sslmode=disable&search_path=account_service"

[account.cookie]
# Set to true if served over HTTPS.
secure = true

# SameSite policy of cookie.
# Should be one of: 'strict', 'lax' or 'none'.
same_site = "lax"

[account.redis]
# Connection address of redis.
addr = "localhost:6379"

[account.rabbitmq]
# Broker URL of RabbitMQ.
broker_url = "amqp://community:community_dev_password@localhost:5672/"

[account.jwt]
# JWT Secret.
# Should be more than 32 bytes.
# NOTE: Never expose this to public repository.
secret = ""

[account.snowflake]
# Node ID for snowflake.
node_id = 1

[account.token]
# Token issuer name.
issuer = "account-service"

# Validity of access token.
access_token_validity = "2h"

[account.slog]
# Handler type of slog.
# Should be one of: 'default', 'discard', 'text', 'json' or 'tint'.
type = "tint"

# Log level of slog.
# Should be one of: 'debug', 'info', 'warn' or 'error'.
# Note: Ignored when 'type' is 'default' or 'discard'.
level = "debug"

[account.slog.tint]
# Time format when the handler type is 'tint'.
# Should be one of: 'rfc3339', 'rfc3339_nano', 'stamp', 'stamp_milli', 'stamp_micro', 
# 'stamp_nano', 'kitchen', 'ruby', 'layout', 'date_time', 'ansic' or 'unix_date'.
time_format = "stamp_milli"

[account.gorm]
# Whether to skip default transaction in Gorm.
skip_default_transaction = true

# Whether to prepare statements.
prepare_stmt = false

# Whether to disable foreign key constraint when migrating.
disable_foreign_key_constraint_when_migrating = true

[account.gorm.logger]
# Log level of Gorm logger.
# Should be one of: 'silent', 'info', 'warn' or 'error'.
level = "info"

# Threshold for slow query logging.
slow_threshold = "200ms"

# Whether to ignore record not found error.
ignore_record_not_found_error = true

# Whether to use parameterized queries in logs.
parameterized_query = true

# Whether to enable colorful logging.
# Deprecated: This option is no longer effective since Gorm's logger is now implemented via slog.
# If you need colorful output, configure the 'tint' handler in [account.slog] instead.
colorful = true

[account.gin]
# Run mode of Gin framework.
# Should be one of: 'debug', 'release' or 'test'.
mode = "debug"
